terraform {
  required_version = ">= 1.5.0"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
    azuread = {
      source  = "hashicorp/azuread"
      version = "~> 2.0"
    }
  }

  # Recommended for production: store state remotely with locking, e.g.
  # backend "azurerm" {
  #   resource_group_name  = "tfstate-rg"
  #   storage_account_name = "mytfstateaccount"
  #   container_name        = "tfstate"
  #   key                   = "diagram-agent.tfstate"
  # }
}

provider "azurerm" {
  features {}
}

provider "azuread" {}

# >>> archly:group:vnet1 >>>
# VNet (network boundary)

resource "azurerm_virtual_network" "vnet1" {
  name                = "vnet1"
  resource_group_name = var.resource_group_name
  location            = var.location
  address_space       = [var.vnet1_address_space]
}
# <<< archly:group:vnet1 <<<

# >>> archly:group:subnet1 >>>
# App Subnet (subnet within 'VNet')

resource "azurerm_subnet" "subnet1" {
  name                 = "subnet1"
  resource_group_name  = var.resource_group_name
  virtual_network_name = azurerm_virtual_network.vnet1.name
  address_prefixes     = [var.subnet1_address_prefix]
}
# <<< archly:group:subnet1 <<<

# >>> archly:group:subnet2 >>>
# Data Subnet (subnet within 'VNet')

resource "azurerm_subnet" "subnet2" {
  name                 = "subnet2"
  resource_group_name  = var.resource_group_name
  virtual_network_name = azurerm_virtual_network.vnet1.name
  address_prefixes     = [var.subnet2_address_prefix]
}
# <<< archly:group:subnet2 <<<

# >>> archly:node:afd1 >>>
# Azure Front Door (cdn)
resource "azurerm_cdn_endpoint" "afd1" {
  name                = "afd1"
  profile_name        = var.afd1_cdn_profile_name
  location            = var.location
  resource_group_name = var.resource_group_name
  origin {
    name      = "afd1-origin"
    host_name = var.afd1_origin_host_name
  }
}
# <<< archly:node:afd1 <<<

# >>> archly:node:waf1 >>>
# App Gateway WAF (firewall)
resource "azurerm_web_application_firewall_policy" "waf1" {
  name                = "waf1"
  resource_group_name = var.resource_group_name
  location            = var.location
  managed_rules {
    managed_rule_set {
      type    = "OWASP"
      version = "3.2"
    }
  }
}
# <<< archly:node:waf1 <<<

# >>> archly:node:container1 >>>
# Container Apps (compute.container) -- belongs to subnet 'App Subnet' (see resource id 'subnet1' above; wire this resource's subnet/network args to it manually)
resource "azurerm_container_app" "container1" {
  name                         = "container1"
  resource_group_name          = var.resource_group_name
  container_app_environment_id = var.container1_environment_id
  revision_mode                = "Single"
  template {
    container {
      name   = "container1"
      image  = var.container1_container_image
      cpu    = 0.5
      memory = "1Gi"
    }
  }
}
# <<< archly:node:container1 <<<

# >>> archly:node:sql1 >>>
# Azure SQL (database.relational) -- belongs to subnet 'Data Subnet' (see resource id 'subnet2' above; wire this resource's subnet/network args to it manually)
resource "azurerm_postgresql_flexible_server" "sql1" {
  name                   = "sql1"
  resource_group_name    = var.resource_group_name
  location               = var.location
  administrator_login    = var.sql1_administrator_login
  administrator_password = var.sql1_administrator_password
  sku_name               = "B_Standard_B1ms"
  storage_mb             = 32768
  version                = "15"
}
# <<< archly:node:sql1 <<<

# >>> archly:node:redis1 >>>
# Cache for Redis (database.cache) -- belongs to subnet 'Data Subnet' (see resource id 'subnet2' above; wire this resource's subnet/network args to it manually)
resource "azurerm_redis_cache" "redis1" {
  name                = "redis1"
  resource_group_name = var.resource_group_name
  location            = var.location
  capacity            = 1
  family              = "C"
  sku_name            = "Standard"
  # Access keys are generated by Azure and available as sensitive outputs
  # (azurerm_redis_cache.redis1.primary_access_key) -- never set them as input.
}
# <<< archly:node:redis1 <<<

# >>> archly:node:bus1 >>>
# Service Bus (queue)
resource "azurerm_servicebus_queue" "bus1" {
  name         = "bus1"
  namespace_id = var.bus1_servicebus_namespace_id
}
# <<< archly:node:bus1 <<<

# >>> archly:node:blob1 >>>
# Blob Storage (storage.object)
resource "azurerm_storage_account" "blob1" {
  name                     = var.blob1_storage_account_name
  resource_group_name      = var.resource_group_name
  location                 = var.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  min_tls_version          = "TLS1_2"
}
# <<< archly:node:blob1 <<<

# >>> archly:node:vault1 >>>
# Key Vault (secrets)
resource "azurerm_key_vault" "vault1" {
  name                       = "vault1"
  resource_group_name        = var.resource_group_name
  location                   = var.location
  tenant_id                  = var.tenant_id
  sku_name                   = "standard"
  purge_protection_enabled   = true
  soft_delete_retention_days = 90
}
# <<< archly:node:vault1 <<<